services:
  postgres:
    image: postgres:15
    container_name: freelearningchat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - freelearningchat-network

volumes:
  postgres_data:

networks:
  freelearningchat-network:
    driver: bridge
